
name: dbt Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: xemuliam/dbt

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Push changes.
        env: 
          git_pass: ${{SECRETS.DBT}} 
          gitp: ${{SECRETS.gitp}}
          gitu: ${{SECRETS.gitu}}
        run: |
          apt-get install -y git
          dbt --help
          # git clone https://github.com/supriya7348/dbt_github2.git
                    
          # cd ./dbt_github2
          # git config --global user.email "priyasupriya2018@gmail.com"
          # git config --global user.name "supriya7348"
          # dbt seed
          # dbt test
          # dbt docs generate
          # cp -u -r target docs
          # git add .
          # git commit -m "[skip ci] Added pages"
          # git push https://$git_pass@github.com/supriya7348/dbt_github2.git