name: Run dbt with Docker

on:
  push:
    branches:
      - main

jobs:
  dbt_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run dbt Docker Container
      run: |
        docker run --rm -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app xemuliam/dbt dbt run
    - name: Run dbt seeds
      run: |
        docker run --rm -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app xemuliam/dbt dbt seed

    - name: Run dbt tests
      run: |
        docker run --rm -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app xemuliam/dbt dbt test
    
    - name: Generate dbt Documentation
      run: |
        docker run --rm -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app xemuliam/dbt dbt docs generate
    

    - name: Commit and Push "target" Folder
      run: |
          git add target/
          git commit -m "Add 'target' folder"
          git push
    # - name: Serve dbt Documentation
    #   run: |
    #     docker run --rm -v ${{ github.workspace }}:/usr/src/app -p 8080:8080 -w /usr/src/app xemuliam/dbt dbt docs serve
  
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
          name: dbt_target
          path: target